# Solarized Dark theme for gum
# Global Style
set -Ux GUM_STYLE_FOREGROUND '#839496'
set -Ux GUM_STYLE_BORDER_FOREGROUND '#268bd2'
# Choose
set -Ux GUM_CHOOSE_CURSOR_FOREGROUND '#268bd2'
set -Ux GUM_CHOOSE_HEADER_FOREGROUND '#586e75'
set -Ux GUM_CHOOSE_SELECTED_FOREGROUND '#859900'
# Confirm
set -Ux GUM_CONFIRM_PROMPT_FOREGROUND '#839496'
set -Ux GUM_CONFIRM_SELECTED_BACKGROUND '#268bd2'
set -Ux GUM_CONFIRM_SELECTED_FOREGROUND '#fdf6e3'
set -Ux GUM_CONFIRM_UNSELECTED_BACKGROUND '#073642'
set -Ux GUM_CONFIRM_UNSELECTED_FOREGROUND '#586e75'
# File Picker (consistent with your .dircolors)
set -Ux GUM_FILE_CURSOR_FOREGROUND '#268bd2'
set -Ux GUM_FILE_DIRECTORY_FOREGROUND '#2aa198' # Matches DIR 36
set -Ux GUM_FILE_SYMLINK_FOREGROUND '#d33682' # Matches LINK 35
set -Ux GUM_FILE_SELECTED_FOREGROUND '#859900'
set -Ux GUM_FILE_HEADER_FOREGROUND '#586e75'
set -Ux GUM_FILE_PERMISSIONS_FOREGROUND '#586e75'
# Filter
set -Ux GUM_FILTER_INDICATOR_FOREGROUND '#268bd2'
set -Ux GUM_FILTER_MATCH_FOREGROUND '#2aa198'
set -Ux GUM_FILTER_PROMPT_FOREGROUND '#268bd2'
set -Ux GUM_FILTER_HEADER_FOREGROUND '#586e75'
set -Ux GUM_FILTER_PLACEHOLDER_FOREGROUND '#586e75'
# Input
set -Ux GUM_INPUT_PROMPT_FOREGROUND '#268bd2'
set -Ux GUM_INPUT_CURSOR_FOREGROUND '#268bd2'
set -Ux GUM_INPUT_HEADER_FOREGROUND '#586e75'
set -Ux GUM_INPUT_PLACEHOLDER_FOREGROUND '#586e75'
# Log
set -Ux GUM_LOG_LEVEL_FOREGROUND '#586e75'
set -Ux GUM_LOG_TIME_FOREGROUND '#586e75'
set -Ux GUM_LOG_PREFIX_FOREGROUND '#268bd2'
set -Ux GUM_LOG_MESSAGE_FOREGROUND '#839496'
# Pager
set -Ux GUM_PAGER_FOREGROUND '#839496'
set -Ux GUM_PAGER_LINE_NUMBER_FOREGROUND '#586e75'
set -Ux GUM_PAGER_MATCH_FOREGROUND '#2aa198'
set -Ux GUM_PAGER_HELP_FOREGROUND '#586e75'
# Spin
set -Ux GUM_SPIN_SPINNER_FOREGROUND '#268bd2'
set -Ux GUM_SPIN_TITLE_FOREGROUND '#839496'
# Table
set -Ux GUM_TABLE_BORDER_FOREGROUND '#268bd2'
set -Ux GUM_TABLE_HEADER_FOREGROUND '#586e75'
set -Ux GUM_TABLE_SELECTED_BACKGROUND '#268bd2'
set -Ux GUM_TABLE_SELECTED_FOREGROUND '#fdf6e3'
# Write
set -Ux GUM_WRITE_PROMPT_FOREGROUND '#268bd2'
set -Ux GUM_WRITE_CURSOR_FOREGROUND '#268bd2'
set -Ux GUM_WRITE_HEADER_FOREGROUND '#586e75'
set -Ux GUM_WRITE_PLACEHOLDER_FOREGROUND '#586e75'
