#!/usr/bin/env fish
show trash ~/Desktop/*.png
show brew cleanup
show brew services cleanup
show n prune
show docker-start
show docker-clean --stop
show docker-clean
show docker-clean --networks --containers
show docker builder prune --all --force
