#!/usr/bin/env fish
show rm -rf \
 $HOME/.m2/repository/ \
 $HOME/Library/Caches/* \
 $HOME/DryCache \
 $HOME/.vagrant.d \
 $HOME/.npm/_cacache

for image in (docker image ls --format '{{.ID}}')
	show docker image rm --force $image
end

#TODO clean project dirs
# .shadow-cljs
# .cpcache
# .clj-kondo/.cache
# .vagrant
# node_modules
# target
