#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
dest=~/.dircolors
if [ ! -e $dest ]; then
	curl -o $dest https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-universal
fi
