#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
export ASDF_PYTHON_VERSION=latest
asdf reshim python
asdf install awscli latest
asdf global awscli latest
asdf-uninstall-old awscli
aws --version
