#!/usr/bin/env bash
source ~/strict.bash

command_exists () {
  command -v $1 >/dev/null 2>&1
}

if ! command_exists brew;then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ $(which ruby)  = '/usr/bin/ruby' ];then
	brew install ruby
fi

exec ./install-bundle
exec ./install-node
exec ./install-python
