#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
brew-force-uninstall dotnet dotnet-sdk
mise install dotnet-core@latest
mise use --global dotnet-core@latest
mise-uninstall-old dotnet-core
