#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
#TODO set version to 'latest' once https://github.com/emersonsoares/asdf-dotnet-core/issues/37 is fixed
version='8.0.200'
asdf install dotnet-core $version
asdf global dotnet-core $version
asdf-uninstall-old dotnet-core
