#!/usr/bin/env bash
source ~/strict.bash

version=1.0.0-rc14

file=graalvm-ce-$version-macos-amd64.tar.gz
src=https://github.com/oracle/graal/releases/download/vm-$version/$file
dl=$TMPDIR/$file
echo "Downloading to $src to \$TMPDIR/$file"
aria2c --dir=$TMPDIR $src

echo "Extracting archive"
unar -q -o $TMPDIR $dl 
rm -f $dl

dest=~/GraalVM
echo "Moving to $dest"
rm -rf $dest
mv $TMPDIR/graalvm-ce-$version $dest
