#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
brew-force-uninstall dart dart-sdk flutter
if [ -n "$(brew tap | ag --literal dart-lang/dart)" ]; then
	brew untap dart-lang/dart
fi
asdf install flutter latest || true
asdf set --home flutter latest
asdf reshim flutter
flutter pub cache repair
yes | flutter doctor --android-licenses || true
xargs -L 1 dart pub global activate <"$HOME/Dartfile"
asdf-uninstall-old flutter
