#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"
brew-try-uninstall lua
for name in lua lua-language-server; do
	asdf install $name latest
	asdf set --home $name latest
	asdf-uninstall-old $name
done
