#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"
brew-force-uninstall rust
asdf install rust latest
asdf set --home rust latest
asdf-uninstall-old rust
asdf reshim rust
xargs -L 1 cargo install <"$HOME/Cargofile"
