#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
dir="$(mktemp --directory)"
trap 'rm -rf "$dir"' EXIT
cd "$dir"
aria2c 'https://builds.homerow.app/latest/Homerow.zip'
unzip -q "$dir/Homerow.zip" -d "$dir"
pkill -x Homerow || true
rm -rf /Applications/Homerow.app
mv "$dir/Homerow.app" /Applications/
open -a Homerow
