#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
brew-force-uninstall lua
for name in lua lua-language-server; do
	asdf install $name latest
	asdf global $name latest
	asdf-uninstall-old $name
done
