#!/usr/bin/env bash
source ~/strict.bash
sudo snap remove firefox || true
sudo add-apt-repository ppa:mozillateam/ppa
sudo tee /etc/apt/preferences.d/mozilla-firefox <<- EOM
	Package: *
	Pin: release o=LP-PPA-mozillateam
	Pin-Priority: 1001
EOM
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
sudo apt install firefox
