#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
brew-force-uninstall rust
mise install rust@latest
mise use --global rust@latest
mise-uninstall-old rust
xargs -L 1 cargo install <"$HOME/Cargofile"
