#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"
podman machine init
podman machine start
sudo podman-mac-helper install
podman machine stop
podman machine start
