#!/usr/bin/env bash
source ~/strict.bash
source ~/.jabba/jabba.sh

version='1.8.292-10.1'

jabba install amazon-corretto@$version
jabba use amazon-corretto@$version
jabba alias default amazon-corretto@$version
java -version
