#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
# shellcheck disable=2046
brew-try-uninstall node $(brew list --formula | ag 'node@?')
# Update nodebuild
asdf cmd nodejs update-nodebuild
# Node.js 14
asdf set python latest:3.10
asdf install python
asdf reshim
asdf install nodejs latest:14
# Node.js 16
asdf install nodejs latest:16
# Node.js 20
asdf install nodejs latest:20
# Cleanup old
for version in $(seq 14 23); do
	asdf-uninstall-old nodejs "$version"
done
# latest
asdf install nodejs latest
asdf set --home nodejs latest
asdf reshim nodejs
~/install-npm-packages
