#!/usr/bin/env bash
source ~/strict.bash
asdf install flutter latest
asdf global flutter latest
asdf reshim flutter
flutter pub cache repair
yes | flutter doctor --android-licenses || true
flutter doctor
for tool in stacked_cli webdev;do
	dart pub global activate $tool
done
