#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"

#See https://developer.android.com/studio#command-line-tools-only
version=14742923

dest="$ANDROID_HOME/cmdline-tools/latest"

if [ ! -d "$dest" ]; then
	echo "Downloading ${version}"
	script_name="$(basename "$0")"
	tmpdir="$(mktemp -d -t "${script_name}")"
	trap 'rm -rf "$tmpdir"' EXIT
	file_name="commandlinetools-mac-${version}_latest"
	file="${file_name}.zip"
	aria2c --quiet --dir="$tmpdir" "https://dl.google.com/android/repository/$file"

	echo 'Extracting'
	unar -quiet -output-directory "$tmpdir" -force-directory "$tmpdir/$file"
	mkdir -p "$(dirname "$dest")"
	mv "$tmpdir/$file_name/cmdline-tools" "$dest"
	export PATH="$dest/bin:$PATH"
fi
echo 'Installing'
sdkmanager --install \
	platform-tools \
	emulator \
	'ndk;29.0.14206865' \
	'build-tools;36.1.0' \
	'platforms;android-36.1'

echo 'Checking licences'
sdkmanager --licenses

echo 'Updating'
sdkmanager --update

dest="$ANDROID_HOME/bundletool"
mkdir -p "$dest"
dest="$dest/bundletool.jar"
rm -f "$ANDROID_HOME/bundletool/bundletool.jar"
gh release download \
	--repo 'google/bundletool' \
	--pattern '*-all-*.jar' \
	--output "$dest"
chmod u+x "$dest"
