#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"

#Download iTerm2 shell integration https://www.iterm2.com/documentation-shell-integration.html
shell="$(basename "$SHELL")"
dest="$HOME/.config/iterm2/.iterm2_shell_integration.$shell"
rm -f "$dest"
curl -L "https://iterm2.com/shell_integration/$shell" -o "$dest"

#Download iTerm2 utilities https://www.iterm2.com/documentation-utilities.html
dest="$HOME/iterm-utils"
rm -rf "$dest"
mkdir -p "$dest"
cd "$dest"
git init
git remote add -f origin https://github.com/gnachman/iTerm2-shell-integration.git
git sparse-checkout init
git sparse-checkout set 'utilities'
git pull origin main
