#!/usr/bin/env bash
source ~/strict.bash

echo 'Downloading'
script_name="$(basename "$0")"
tmpdir="$(mktemp -d -t "${script_name}")"
trap "rm -rf '$tmpdir'" EXIT
#See https://developer.android.com/studio#command-line-tools-only
version=9477386
file_name="commandlinetools-mac-${version}_latest"
file="${file_name}.zip"
aria2c --quiet --dir="$tmpdir" "https://dl.google.com/android/repository/$file"

echo 'Extracting'
unar -quiet -output-directory "$tmpdir" -force-directory "$tmpdir/$file"
mkdir -p "$ANDROID_SDK_ROOT"
dest="$ANDROID_SDK_ROOT/cmdline-tools/latest"
mkdir -p "$dest"
rm -rf "$dest"
mv "$tmpdir/$file_name/cmdline-tools" "$dest"
export PATH="$dest/bin:$PATH"

echo 'Installing'
yes | sdkmanager --install \
	emulator \
	'build-tools;33.0.3' \
	platform-tools \
	'platforms;android-33'
