#!/usr/bin/env fish
show asdf install nodejs lts
show asdf install nodejs (asdf latest nodejs 14)
show asdf global nodejs lts
show asdf reshim nodejs
show npm rebuild
#TODO only install if not already installed npm list --global --depth=0 --parseable
if is-linux
	xargs sudo npm install --global < "$HOME/Npmfile"
else
	xargs npm install --global < "$HOME/Npmfile"
end
show asdf reshim nodejs
