#!/usr/bin/env bash
source ~/strict.bash
version=$(asdf latest dart)
asdf install dart $version
asdf global dart $version
for version in 2.16 2.17 2.18;do
	asdf install dart $(asdf latest dart $version)
done
