#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
#shellcheck disable=2046
brew-try-uninstall node $(brew list --formula | ag 'node@?')
for version in \
	latest:16 \
	latest:18 \
	latest; do
	asdf install nodejs $version
done
for version in \
	16 \
	18 \
	22; do
	asdf-uninstall-old nodejs $version
done
asdf global nodejs latest
~/install-npm-packages
