#!/usr/bin/env bash
source ~/strict.bash
set -e
if is-linux;then
	curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
	sudo apt install -y nodejs
	sudo apt autoremove
fi
if is-mac;then
	brew unlink node || true
	brew unlink node node@14 || true
	brew link --overwrite node@12
fi
npm rebuild
#TODO only install if not already installed npm list --global --depth=0 --parseable
if is-linux;then
	xargs sudo npm install --global < $HOME/Npmfile
else
	xargs npm install --global < $HOME/Npmfile
fi
