#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
brew-force-uninstall dotnet dotnet-sdk
asdf install dotnet-core latest
asdf set --home dotnet-core latest
asdf-uninstall-old dotnet-core
