#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"

echo 'Downloading'
script_name="$(basename "$0")"
tmpdir="$(mktemp -d -t "${script_name}")"
trap 'rm -rf "$tmpdir"' EXIT
#See https://developer.android.com/studio#command-line-tools-only
version=11076708
file_name="commandlinetools-mac-${version}_latest"
file="${file_name}.zip"
aria2c --quiet --dir="$tmpdir" "https://dl.google.com/android/repository/$file"

echo 'Extracting'
unar -quiet -output-directory "$tmpdir" -force-directory "$tmpdir/$file"
mkdir -p "$ANDROID_HOME"
dest="$ANDROID_HOME/cmdline-tools/latest"
mkdir -p "$dest"
rm -rf "$dest"
mv "$tmpdir/$file_name/cmdline-tools" "$dest"
export PATH="$dest/bin:$PATH"

echo 'Installing'
sdkmanager --install \
	platform-tools \
	emulator \
	'ndk;27.0.11902837' \
	'build-tools;35.0.0-rc4' \
	'platforms;android-34'

echo 'Checking licences'
sdkmanager --licenses

dest="$ANDROID_HOME/bundletool"
mkdir -p "$dest"
dest="$dest/bundletool.jar"
rm -f "$ANDROID_HOME/bundletool/bundletool.jar"
gh release download \
	--repo 'google/bundletool' \
	--pattern '*-all-*.jar' \
	--output "$dest"
chmod u+x "$dest"
