#!/usr/bin/env bash
source ~/strict.bash
asdf install nodejs latest:18
asdf install nodejs latest
asdf global nodejs latest
npm rebuild
#TODO only install if not already installed npm list --global --depth=0 --parseable
if is-linux;then
	xargs sudo npm install --global < "$HOME/Npmfile"
else
	xargs npm install --global < "$HOME/Npmfile"
fi
