#!/usr/bin/env bash
source ~/strict.bash

command-exists () {
  command -v $1 >/dev/null 2>&1
}

if ! command-exists ruby;then
	echo 'Ruby is not installed'
	exit 1
fi

if ! command-exists brew;then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

#FIXME add brew to the path
#/home/linuxbrew/.linuxbrew/bin

if is-mac;then
	./install-bundle
fi
./install-node
./install-python
./install-dircolors
