#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
mise plugin add ghc https://github.com/mise-plugins/mise-ghcup.git
version=9.8.2
mise install ghc@$version
mise use --global ghc@$version
mise install cabal@latest stack@latest
mise use --global cabal@latest stack@latest
