#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
./install-homebrew
./install-bundle
./install-omf
./install-android-sdk
./install-asdf
./install-dircolors
./install-vim-plug
./install-fonts
./install-iterm-scripts
./install-jesi-dotfiles
./install-deno
./install-rust
./install-java
./install-nodejs
.vim/install.fish
.hammerspoon/install-spoons.sh
./update
