#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
for version in \
	latest:16 \
	latest:18 \
	18.17.0 \
	latest; do
	asdf install nodejs $version
done
for old_version in \
	16 \
	21; do
	asdf-uninstall-old nodejs $old_version
done
asdf global nodejs latest
~/install-npm-packages
