#!/usr/bin/env fish
echo 'Updating .Brewfile'
brew bundle dump --force --global

echo 'Updating Npmfile'
npm list --global --depth=0 --parseable 2>/dev/null | 
	ag --only-matching '(?<=\/node_modules\/).+$(?<!npm)' > Npmfile

echo 'Updating Fisherfile'
fisher list > Fisherfile

echo 'Updating .asdf-plugins'
asdf plugin list --urls > .asdf-plugins

echo 'Updating Dartfile'
dart pub global list | cut -d ' ' -f1 > Dartfile
