#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
line=service-db:keyfile/user
file=/etc/dconf/profile/user
ag --silent --literal "$line" "$file" >/dev/null || echo "$line" | sudo tee --append "$file"
