#!/usr/bin/env bash
source "$HOME/.bash_functions/strict.bash"
sudo mkdir -p /etc/firefox/defaults/pref/
cd /etc/firefox
sudo tee defaults/pref/autoconfig.js >/dev/null <<-CONFIG
	pref('general.config.filename', 'config.js');
	pref('general.config.obscure_value', 0);
CONFIG
sudo tee config.js >/dev/null <<-CONFIG
	// IMPORTANT: Start your code on the 2nd line
	displayError('config.js', 'Here!');
CONFIG
