#!/usr/bin/env fish
# https://github.com/IlanCosman/tide/wiki/Syncing-your-tide-config-in-your-dotfiles
tide configure --auto \
    --style=Rainbow \
    --prompt_colors='16 colors' \
    --show_time='24-hour format' \
    --rainbow_prompt_separators=Angled \
    --powerline_prompt_heads=Sharp \
    --powerline_prompt_tails=Flat \
    --powerline_prompt_style='One line' \
    --prompt_spacing=Compact \
    --icons='Many icons' \
    --transient=Yes
# https://github.com/IlanCosman/tide/wiki/Configuration
set --universal tide_right_prompt_items status cmd_duration context jobs direnv time
