#!/usr/bin/env fish
tide configure --auto \
    --style=Rainbow \
    --prompt_colors='True color' \
    --show_time='24-hour format' \
    --rainbow_prompt_separators=Angled \
    --powerline_prompt_heads=Sharp \
    --powerline_prompt_tails=Flat \
    --powerline_prompt_style='One line' \
    --prompt_spacing=Compact \
    --icons='Many icons' \
    --transient=Yes
