#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# in fish:
#alias .f='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
#alias .s='git --git-dir=$HOME/.dotfiles-secret/ --work-tree=$HOME'

# run: https://github.com/AndreTheHunter/dotfiles/blob/master/set-dotfiles-repos

./install
