#!/usr/bin/env bash
#shellcheck source=strict.bash
source ~/strict.bash
app='IntelliJ IDEA Ultimate.app'
ln -s -f \
	"$HOME/Library/Application Support/JetBrains/Toolbox/scripts/$app" \
	"/Applications/$app"
