#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"
node="$(realpath "$(which node)")"
/usr/libexec/ApplicationFirewall/socketfilterfw --remove "$(which node)"
/usr/libexec/ApplicationFirewall/socketfilterfw --remove "$node"
#codesign --force --sign - "$node"
/usr/libexec/ApplicationFirewall/socketfilterfw --add "$node"
