#!/usr/bin/env fish
for dir in (find $JESI_PROJECTS -type d -depth 1 -maxdepth 1)
	cd "$dir"
	if git is-git
		set_color yellow
		echo "Updating project $dir"
		set_color normal
		git fe
		git prune-merged
		git submodule foreach --recursive git prune-merged
	end
	cd -
end

