#!/usr/bin/env bash
#shellcheck source-path=..
source "$HOME/.bash_functions/strict.bash"
outdated="$(npm_outdated)"
if [ -n "$outdated" ]; then
	npm install --global "$outdated"
fi
corepack enable
asdf reshim nodejs
