#!/usr/bin/env fish
show softwareupdate --all --install --force --verbose
show mas upgrade
show brew update
show brew upgrade
show brew unlink awscli;and show brew link awscli@1
show brew unlink node node@14;and show brew link --overwrite node@12
show omf update
show fisher update

show tfenv install latest
#show tfenv use latest

show flutter upgrade

function npm-outdated
	npm outdated --global --parseable | ag --only-matching '(?<=/node_modules/).+?(?=:)'
end

if npm-outdated | ag --silent --literal 'npm' >/dev/null
	show npm install --global --force npm
end

for module in (npm-outdated)
	show npm install --global $module
end
show npm install --global local-web-server@4
show npm rebuild

#show gem update --system
#show gem update
#show bundle update
show ngrok update

for pkg in (pip3 list --outdated --format freeze | ag --only-matching '.+(?===)')
	show pip3 install --upgrade $pkg 
end
show pip3 check

show ~/.vim/install.fish

show ~/.spacemacs.d/update.sh

show curl https://raw.githubusercontent.com/axrs/cljog/master/cljog -o /usr/local/bin/cljog
show cljog --update

show tldr --update

#pwsh -Command Update-Help

show gcloud components update --quiet

show ~/update-projects
show ~/patch
show fish_update_completions
show ~/save
