#!/usr/bin/env fish
if is-mac
	show softwareupdate --download --verbose
	show softwareupdate --install --all --verbose
	show mas upgrade
end
show brew update
show brew upgrade
show brew unlink ghostscript php
show brew cleanup
show omf update
show fisher update
show asdf plugin update --all
show ~/install-java
show ~/install-python
show ~/install-dotnet
show ~/install-node
show ~/install-ruby
show ~/install-flutter
show ~/install-dart
show ~/install-terraform
show ~/install-awscli
show ~/install-azure-cli
show npm install --global npm
for module in (npm_outdated)
	show npm install --global $module
end
show npm install --global local-web-server@4 #lock version
show sdkmanager --update
#show gem update --system
#show gem update
#show bundle update
show ngrok update
~/.vim/install.fish
show tldr --update
#pwsh -Command Update-Help
show ~/update-projects
optional-source "$HOME/secret/update.fish"
show fish_update_completions
show ~/save
