#!/usr/bin/env fish
show softwareupdate --install --all --verbose
show mas upgrade
show brew update
show brew upgrade
show n stable

function npm-outdated
	npm outdated --global --parseable | ag --only-matching '(?<=/node_modules/).+?(?=:)'
end

if npm-outdated | ag --silent --literal 'npm' >/dev/null
	show npm install --global npm
end

for module in (npm-outdated)
	show npm install --global $module
end
show npm rebuild

show gem update --system
#show gem update
#show bundle update
show omf update
show ngrok update

for pkg in (pip3 list --outdated --format freeze | ag --only-matching '.+(?===)')
	show pip3 install --upgrade $pkg 
end
#since pip can break awscli sometimes:
show pip3 install -U awscli

for cask in (brew cask outdated | ag --only-matching '.+')
	show brew cask reinstall $cask
end

show ~/.vim/install.fish

show ~/.spacemacs.d/update.sh

show tfenv install latest

show sdkmanager --update

show curl https://raw.githubusercontent.com/axrs/cljog/master/cljog -o /usr/local/bin/cljog
show cljog --update

for dir in (ls -d $JESI_PROJECTS/*)
	show cd "$dir"
	if git is-git
		show git fe
		show git prune-merged
		show git gc --aggressive 
	end
	cd -
end

show ~/clean
show fish_update_completions
show ~/save
