"TODO
" insert newline before .
" fix indentation on paste

source ~/.vim/ale.vim
source ~/.vim/install-vim-plug.vim

call plug#begin('~/.vim/plugged')
source ~/.vim/plugins.vim
call plug#end()

source ~/.vim/common.vim

set backupdir=/tmp//
set directory=/tmp//
set undodir=/tmp//
