"TODO
" insert newline before .
" fix indentation on paste
source ~/.vim/install-vim-plug.vim
call plug#begin('~/.vim/plugged')
source ~/.vim/plugins.vim
call plug#end()
augroup vim_plug_sync
	autocmd VimEnter *
  			\  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  			\|   PlugInstall --sync | q
  			\| endif
augroup end
source ~/.vim/common.vim
let g:ale_fix_on_save = 1
let g:ale_fixers = { '*': ['remove_trailing_lines', 'trim_whitespace'] }
"let g:ale_lint_on_enter = 0
"let g:ale_lint_on_insert_leave = 0
"let g:ale_lint_on_text_changed = 'never'
set backupdir=/tmp//
set directory=/tmp//
set undodir=/tmp//
