"$schema" = 'https://starship.rs/config-schema.json'

#TODO match https://github.com/oh-my-fish/theme-bobthefish

#based on https://gist.github.com/notheotherben/92302a60f8599ba73f1c2840f3c6d455
#FIXME use a colour palettes
format = """
[\uE0B6](fg:#1C4961)[$directory](bg:#1C4961)\
[\uE0B0](fg:#1C4961 bg:#2F79A1)$git_branch\
[\uE0B0](fg:#2F79A1 bg:#3A95C7)$git_status\
[\uE0B0](#40A9E0 bg:none)$character\
"""
add_newline = false
right_format = "$all$cmd_duration$time"
palette = 'solarized'

[palettes.solarized]
darkgreen = "22"
brightgreen = "148"
white = "15"
dimwhite = "250"
babyblue = "4"
mediumgrey = "240"
darkgrey = "236"
burgundy = "52"

[directory]
truncate_to_repo = false
#FIXME show dir path, then git, then repo dir
#format = "[$symbol$branch]($style)"
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)\
"""
style = "bg:#1C4961 fg:white"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bg:#2F79A1 fg:white"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bg:#3A95C7 fg:white"

[character]
format = "$symbol"

[line_break]
disabled = true

[time]
disabled = false
time_format = "%H:%M"

[cmd_duration]
min_time = 500
show_milliseconds = true
